"""Generated by tools/update_versions.sh — do not edit by hand.

Schema:

    CERT_MANAGER_VERSIONS = {
        "<version>": {
            "url": "<URL of cert-manager.yaml release asset>",
            "sha256": "<sha256>",
        },
    }

Maintainer flow:
    bash tools/update_versions.sh <version>            # add or update
    bash tools/update_versions.sh <version> --update   # also auto-edit
"""

CERT_MANAGER_VERSIONS = {
    "1.18.3": {
        "url": "https://github.com/cert-manager/cert-manager/releases/download/v1.18.3/cert-manager.yaml",
        "sha256": "f12a78d93d77e1eb9dea0b6d7c931b26da287492fcdf0eb58620142883d4675a",
    },
}

PLATFORMS = {
    "darwin_amd64": ["@platforms//os:osx", "@platforms//cpu:x86_64"],
    "darwin_arm64": ["@platforms//os:osx", "@platforms//cpu:arm64"],
    "linux_amd64": ["@platforms//os:linux", "@platforms//cpu:x86_64"],
}
